spring:
    application:
        name: bio
    profiles:
        active: dev
    servlet:
        multipart:
            max-request-size: 1200MB
            max-file-size: 1024MB

logging:
    level:
      com.xjtlu.bio: DEBUG

mybatis:
    mapper-locations: classpath*:mapper/*.xml
    type-aliases-package: com.example.bio.entity
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: true

server:
    port: 8080
    servlet:
        session:
            timeout: 2h 
api:
    login: "user/login"
    logout: "user/logout"

             
            
        


    
