spring:
    datasource:
        url: jdbc:mysql://localhost:3306/bio
        username: bio_dev
        password: '062400'
        driver-class-name: com.mysql.cj.jdbc.Driver




localstorageService:
    baseDir: /home/jcy/bio_app_data/storage


refSeqService:
    base: /home/jcy/bio_app_data/refseqService
    nonInnerRefSeqDir: ${refSeqService.base}/nonInnerRefSeqDir
    temporaryPath: ${refSeqService.base}/temp
    refSeqIndexDir: ${refSeqService.base}/index
    refseqsDir: /home/jcy/bioData/refseq
    virusIndexPath: ${refSeqService.base}/



analysisPipeline:


    conda: "conda"

    tools:
        fastp:
            - "conda"
            - "run"
            - "-n"
            - "bio-fastp"
            - "fastp"
        spades:
            - "conda"
            - "run"
            - "-n"
            - "bio-spades"
            - "spades.py"
        samtools:
            - "conda"
            - "run"
            - "-n"
            - "bio-map"
            - "samtools"
        minimap2:
            - "conda"
            - "run"
            - "-n"
            - "bio-map"
            - "minimap2"
        bcftools:
            - "conda"
            - "run"
            - "-n"
            - "bio-var"
            - "bcftools"

    stage:
        baseInputDir: /home/jcy/bio_app_data/temp/stage/input
        baseWorkDir: /home/jcy/bio_app_data//temp/stage/work




