spring:
    datasource:
        url: jdbc:mysql://localhost:3306/bio?rewriteBatchedStatements=true
        username: bio_dev
        password: '062400'
        driver-class-name: com.mysql.cj.jdbc.Driver




localstorageService:
    baseDir: /home/jcy/bio_app_data/storage
    temporaryPath: /home/jcy/bio_app_data/tmp


refSeqService:
    base: /home/jcy/bio_app_data/refseqService
    nonInnerRefSeqDir: ${refSeqService.base}/nonInnerRefSeqDir
    temporaryPath: ${refSeqService.base}/temp
    refSeqIndexDir: ${refSeqService.base}/index
    refseqsDir: /home/jcy/bioData/refseq
    virusIndexPath: ${refSeqService.base}/



analysis-pipeline:


    conda: "/usr/conda/condabin/conda"

    tools:
        fastp: ["${analysis-pipeline.conda}", "run", "-n", "bio-fastp","fastp"]
        spades: ["${analysis-pipeline.conda}", "run", "-n", "bio-spades", "spades.py"]
        samtools: ["${analysis-pipeline.conda}", "run", "-n", "bio-map", "samtools"]
        # minimap2: ["${analysis-pipeline.conda}", "run", "-n", "bio-map", "minimap2"]
        minimap2: ["/usr/conda/envs/bio-map/bin/minimap2"]
        bcftools: ["${analysis-pipeline.conda}", "run", "-n", "bio-var", "bcftools"]
        amrfinder: ["${analysis-pipeline.conda}", "run", "-n", "amrfinder", "amrfinder"]
        virulenceFactor: ["${analysis-pipeline.conda}", "run", "-n", "virulence", "abricate"]
        mlst: ["${analysis-pipeline.conda}", "run", "-n", "mlst", "mlst"]
        kraken2: ["${analysis-pipeline.conda}", "run", "-n", "bio-kraken", "kraken2", "--db", "~/refereceTmp/kraken_db"]
        seqsero2: ["${analysis-pipeline.conda}", "run", "-n", "seqsero2", "SeqSero2_package.py"]
        ectyper: ["${analysis-pipeline.conda}", "run", "-n", "ectyper", "ectyper"]
        kaptive: ["${analysis-pipeline.conda}", "run", "-n", "kaptive", "kaptive", "-k", "/home/jcy/refereceTmp/kaptive_db"]
        seroBA: ["${analysis-pipeline.conda}", "run", "-n", "seroba", "seroba"]
        

    stage:
        baseInputDir: /home/jcy/bio_app_data/temp/stage/input
        baseWorkDir: /home/jcy/bio_app_data//temp/stage/work

        qc: 
            r1FileName: "cleaned_r1.fastq.gz"
            r2FileName: "cleaned_r2.fastq.gz"
            HTMLFileName: "cleaned.html"
            JSONFileName: "cleaned.json"
        assembly:
            contigsFileName: "contigs.fasta"
            scaffoldFileName: "scaffolds.fasta"
        mapping:
            bamFileName: "result.bam"
            bamIndexFileName: "result.bam.bai"
        variant:
            vcfFileName: "variants.vcf.gz"
            vcfIndexFileName: "variants.vcf.gz.tbi"
        consensus:
            fastaFileName: "consensus.fasta"
            maskBedFileName: "consensus.mask.bed"   # 可选
            qcFileName: "consensus.qc.json"         # 可选（覆盖率/缺失率）
        mlst:
            tsvFileName: "mlst.tsv"
            jsonFileName: "mlst.json"
        amr:
            tsvFileName: "amr.tsv"
            jsonFileName: "amr.json"
            summaryFileName: "amr.summary.json"
        
        
        
        




