spring:
    application:
        name: bio

    datasource:
        url: jdbc:mysql://localhost:3306/bio
        username: bio_dev
        password: '062400'
        driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
    mapper-locations: classpath*:mapper/**/*.xml
    type-aliases-package: com.example.bio.entity
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: true

server:
    port: 8080


    servlet:
        session:
            timeout: 2h 
api:
    login: "user/login"
    logout: "user/logout"

minio:
    user: minioadmin
    password: minioadmin
    url: "http://localhost:9000"

    expose-url: http://localhosts:3306
    bucket: "bio-bucket"


localStorage:
    tmp: "/data/bioServer/tmp"


refSeq:
    virus: /data/refs/ncbi_dataset/data
    virus-index: /data/refs/ncbi_dataset/data/assembly_data_report.jsonl

analysisPipeline:
    stage:
        qc:
            cmd: fastq


    
